# -*- coding: utf-8 -*-
"""generate_embeddings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MBkZzIYHHEY_shDiTUH8hryEqVWUluYd
"""

!pip install fair-esm
!pip install torch
!pip install tqdm

import torch
import esm
import pandas as pd
import numpy as np
from tqdm import tqdm

from google.colab import drive
drive.mount('/content/drive')

# Step 1: Loading the dataset
#Loading the dataset

df = pd.read_csv('//content/drive/MyDrive/DL/modified_data.csv')

#Preview the dataset
print(df.index)
df.head()

# Step 2: Preparing the embedder

# Loading the ESM model
model, alphabet = esm.pretrained.esm2_t6_8M_UR50D()
batch_converter = alphabet.get_batch_converter()
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)
model.eval()

# Prepare the data
sequences = df['Sequence'].tolist()
names = df['Name'].tolist()

# Parameters
batch_size = 8

all_embeddings = []

# Generate embeddings batch-wise
for i in tqdm(range(0, len(sequences), batch_size)):
    batch_labels = names[i:i+batch_size]
    batch_seqs = sequences[i:i+batch_size]
    batch_data = list(zip(batch_labels, batch_seqs))

    # Prepare batch
    batch_labels, batch_strs, batch_tokens = batch_converter(batch_data)
    batch_tokens = batch_tokens.to(device)

    # Pass through model
    with torch.no_grad():
        results = model(batch_tokens, repr_layers=[6])
        token_representations = results["representations"][6]

    # Mean Pooling
    for j, (_, seq) in enumerate(batch_data):
        seq_len = len(seq)
        embedding = token_representations[j, 1:seq_len+1].mean(0)
        all_embeddings.append(embedding.cpu().numpy())

# Convert embeddings list to array
all_embeddings = np.stack(all_embeddings)

# Save embeddings
np.save('esm_embeddings.npy', all_embeddings)

print("✅ Embedding generation complete. Saved as esm_embeddings.npy")